name: hti_indonesia
description: "Human Capital Information Indonesia."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  device_frame: ^1.1.0
  firebase_core: ^2.27.0
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeueMedium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeueBold.ttf
          weight: 600